version: '3'
services:
  app:
    build: .
    container_name: ${{appName}}${{folder_name_sufix}}
    volumes:
      - ${{appName}}${{folder_name_sufix}}:/usr/src/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${{appName}}${{folder_name_sufix}}.rule=Host(`${{appName}}${{folder_name_sufix}}.localhost`)" 
      - "traefik.http.routers.${{appName}}${{folder_name_sufix}}.entrypoints=web"
      - "traefik.http.services.${{appName}}${{folder_name_sufix}}.loadbalancer.server.port=8080" #port that service is exposed
